# Generated by Django 3.2.6 on 2022-02-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.BooleanField(default=False, null=True, verbose_name='Статус'),
        ),
    ]
